I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script call
    call day1
  File "game/script.rpy", line 69, in script
    if len(files) == 0:
  File "game/script.rpy", line 69, in <module>
    if len(files) == 0:
NameError: name 'files' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 27, in script call
    call day1
  File "game/script.rpy", line 69, in script
    if len(files) == 0:
  File "renpy/ast.py", line 1852, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 69, in <module>
    if len(files) == 0:
NameError: name 'files' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
powerplant 1.0
Sun May 30 14:07:08 2021
